version: 0.2
  
phases:
  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - echo "Before running tests"
      - pip install -r requirements.txt

build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - echo "Running all unit tests"
      - python manage.py test      
      
post_build:
    commands:
      -echo build completed on `date` 

artifacts:
  files:
    - '**/*'
cache:
  paths:    
    - 'Devops/**/*'
    - 'budgetapp/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
    - 'manage.py'
    - 'requirements/**/*'
    - 'requirements.txt'
    - 'supervisord.conf'
