version: 0.2

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - sudo ls/root
      # Install dependencies needed for running tests
      - pip install -r requirements/common.txt

  build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - echo "running all unit tests"
      - python manage.py test
  post_build:
    commands:
      -echo build completed on `date` 
artifacts:
  files: 
    - '**/*'
